### ISSUE TITLE
Add INT Managers and INT Team Lead

### ISSUE THREAD

**Issue by FourUnbelievableCoolKids** [WorkMAE/IntegrationFixes#3]
**In COGNOS**

- Please add Christopher Papa and Foziah Alamari (in COGNOS as "Foziah Alamari Foziah Alamari")to the 0.1 RAWDATA COGNOS report
- Please add 43799752 to 0.3 STKHLDR COGNOS report (I do not know Foziah's ID)

**Please change the following formulas in RAWDATA in US-Dash:**

Column AT
=IF(OR($AS2="Jacob Darling",$AS2="Ishan Doray",$AS2="Mahmoud Gaber"),"Active","")

Column AS
=IF(OR($A2="Delphine Corian",$A2="Robert Szmara",$A2="Anthony Ferrando",$A2="Ishan Doray"),"Ishan Doray",IF(OR($A2="Scott Marciano",$A2="David W Sawyer",$A2="Richard Bellamy",$A2="Timothy Sandoval",$A2="Vincent Kan",$A2="Jacob Darling"),"Jacob Darling",IF(OR($A2="Mahmoud Gaber",$A2="Miller Thersea",$A2="Christopher Papa",$A2="Foziah Alamari Foziah Alamari",$A2="Richard Bellamy",$A2="Timothy Sandoval",$A2="Vincent Kan",$A2="Jacob Darling"),"Mahmoud Gaber",IF(OR($A2="Joseph Sliz JR",$A2="Angelica Toie",$A2="Amy Fields",$A2="Nancy Schmitt",$A2="Kimberly Jackson Jackson",$A2="Jon Matias",$A2="Luther Nelson",$A2="Richard Rosenthal",$A2="Homa Alviri",$A2="Amanda McCrea",$A2="Kathleen Stiller",$A2="Cheryl Murawski",$A2="Robin Allen",$A2="Monica Cortez"),"Archived",""))))

Column BA
=IF(OR($A2="Robin Allen",$A2="Cheryl Murawski",$A2="Amy Fields",$A2="Nancy Schmitt"),"Standard File","Complex File")

Column CX
=IF(OR($CW2="Delphine Corian",$CW2="Robert Szmara",$CW2="Anthony Ferrando",$CW2="Ishan Doray"),"Ishan Doray",IF(OR($CW2="Scott Marciano",$CW2="David W Sawyer",$CW2="Richard Bellamy",$CW2="Timothy Sandoval",$CW2="Vincent Kan",$CW2="Jacob Darling"),"Jacob Darling",IF(OR($CW2="Mahmoud Gaber",$CW2="Miller Thersea",$CW2="Christopher Papa",$CW2="Foziah Alamari Foziah Alamari",$CW2="Richard Bellamy",$CW2="Timothy Sandoval",$CW2="Vincent Kan",$CW2="Jacob Darling"),"Mahmoud Gaber",IF(OR($CW2="Joseph Sliz JR",$CW2="Angelica Toie",$CW2="Amy Fields",$CW2="Nancy Schmitt",$CW2="Kimberly Jackson Jackson",$CW2="Jon Matias",$CW2="Luther Nelson",$CW2="Richard Rosenthal",$CW2="Homa Alviri",$CW2="Amanda McCrea",$CW2="Kathleen Stiller",$CW2="Cheryl Murawski",$CW2="Robin Allen",$CW2="Monica Cortez"),"Archived",""))))

Column DK: Rename to Wins awaiting Kickoff, or WaK

Column AU
=IF(OR($J2="Active",$J2="Pre-Sales/RFP",$J2="UAT",$J2="PVT",$J2="Project Scoping",$J2="SIT",$J2="System Setup",$J2="On-Hold",$J2="Not Started",$J2="Interface Dev"),"Desktop","")

**In Daily User Report ...**

In hidden tab titled "Manager VLookup", edit F1 and F2 to reflect your (Metin's) data.  This means your view will be "view all", and I will see only my deal(s).  Currently I get an error due to a conflicting VB lookup.

**Comment by WorkMAE** [comment]
Everything is incorporated and should be fixed

**Comment by FourUnbelievableCoolKids** [comment]
A few notes to review post-changes is any reference to Mahmoud as a Team Lead.

Also, there are hidden rows at the bottom of the Scorecard (1.1) that power the My Score filters.   I believe Foziah and I will need to be added there.

**Comment by FourUnbelievableCoolKids** [comment]
I am not sure what is causing the issue with the User Deck, but I still cannot open without debug errors.  

Debug points here....                 Field.CurrentPage = Sheets("Manager Vlookup").Range("F2").Value

**Comment by FourUnbelievableCoolKids** [comment]
I just realized that in Clientsphere, my name is spelled wrong.  In the filters above, it needs to be amended to read "Christoper Papa" (they omitted the H).

**Comment by WorkMAE** [comment]
Changed the columns in the US Dash to reflect the misspelling...also updated name in Manager VLookup in Daily user report from "Chris Papa" to "Christoper Papa".  should be resolved as of tomorrow.

Do I also need to add you into the Control Panel below on User Report?

![useercp](https://user-images.githubusercontent.com/31932842/33445842-277574ae-d5cc-11e7-872d-042029be2140.PNG)
